blank_issues_enabled: false
contact_links:
  - name: Discuss an idea
    url: https://github.com/tarantool-contrib/rfcs/discussions
    about: Ideas for organization-wide changes start here, before an RFC.
